# Generated by Django 3.2.2 on 2021-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammate',
            name='favorfood',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
