# Generated by Django 3.2.2 on 2021-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_id', models.CharField(max_length=100)),
                ('visitor_password', models.CharField(max_length=100)),
                ('visitor_signupdate', models.DateField()),
            ],
        ),
    ]
