# Generated by Django 3.2.2 on 2021-05-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0002_teammate_favorfood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammate',
            name='favorfood',
            field=models.CharField(max_length=100),
        ),
    ]
