# Generated by Django 3.2.2 on 2021-05-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiger', '0002_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teammate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('nickname', models.CharField(max_length=100)),
                ('introduce', models.TextField()),
                ('mbti', models.CharField(max_length=4)),
                ('hobby', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
